import 'dart:convert';
import 'package:flutter_test/flutter_test.dart';
import 'package:diaspora_handbook/services/qr_service.dart';
import 'package:diaspora_handbook/models/event.dart';
import 'package:flutter/material.dart';

void main() {
  group('QRService', () {
    late QRService qrService;
    late Event testEvent;

    setUp(() {
      qrService = QRService();
      testEvent = Event(
        id: 'test-event-1',
        title: 'Test Event',
        description: 'A test event for QR code generation',
        startTime: DateTime(2025, 1, 15, 18, 0),
        endTime: DateTime(2025, 1, 15, 22, 0),
        location: 'Test Venue',
        category: 'Party',
        color: const Color(0xFFFFD700),
        imageUrl: 'https://example.com/image.jpg',
      );
    });

    group('generateEventQRData', () {
      test('should generate valid JSON string', () {
        final qrData = qrService.generateEventQRData(testEvent);

        expect(qrData, isNotEmpty);
        expect(() => jsonDecode(qrData), returnsNormally);
      });

      test('should include event ID in QR data', () {
        final qrData = qrService.generateEventQRData(testEvent);
        final decoded = jsonDecode(qrData) as Map<String, dynamic>;

        expect(decoded['eventId'], equals('test-event-1'));
      });

      test('should include event title in QR data', () {
        final qrData = qrService.generateEventQRData(testEvent);
        final decoded = jsonDecode(qrData) as Map<String, dynamic>;

        expect(decoded['title'], equals('Test Event'));
      });

      test('should include event location in QR data', () {
        final qrData = qrService.generateEventQRData(testEvent);
        final decoded = jsonDecode(qrData) as Map<String, dynamic>;

        expect(decoded['location'], equals('Test Venue'));
      });

      test('should include startTime in ISO 8601 format', () {
        final qrData = qrService.generateEventQRData(testEvent);
        final decoded = jsonDecode(qrData) as Map<String, dynamic>;

        expect(decoded['startTime'], equals('2025-01-15T18:00:00.000'));
        expect(
          DateTime.parse(decoded['startTime']),
          equals(testEvent.startTime),
        );
      });

      test('should include type field set to event_checkin', () {
        final qrData = qrService.generateEventQRData(testEvent);
        final decoded = jsonDecode(qrData) as Map<String, dynamic>;

        expect(decoded['type'], equals('event_checkin'));
      });
    });

    group('parseQRData', () {
      test('should parse valid QR data', () {
        final validQRData = jsonEncode({
          'eventId': 'test-123',
          'title': 'Test Event',
          'startTime': '2025-01-15T18:00:00.000',
          'location': 'Test Venue',
          'type': 'event_checkin',
        });

        final result = qrService.parseQRData(validQRData);

        expect(result, isNotNull);
        expect(result!['eventId'], equals('test-123'));
        expect(result['title'], equals('Test Event'));
        expect(result['type'], equals('event_checkin'));
      });

      test('should return null for invalid JSON', () {
        const invalidQRData = 'not valid json';

        final result = qrService.parseQRData(invalidQRData);

        expect(result, isNull);
      });

      test('should return null for QR data without type field', () {
        final qrDataWithoutType = jsonEncode({
          'eventId': 'test-123',
          'title': 'Test Event',
        });

        final result = qrService.parseQRData(qrDataWithoutType);

        expect(result, isNull);
      });

      test('should return null for QR data with wrong type', () {
        final qrDataWrongType = jsonEncode({
          'eventId': 'test-123',
          'title': 'Test Event',
          'type': 'wrong_type',
        });

        final result = qrService.parseQRData(qrDataWrongType);

        expect(result, isNull);
      });

      test('should parse data generated by generateEventQRData', () {
        final qrData = qrService.generateEventQRData(testEvent);
        final parsed = qrService.parseQRData(qrData);

        expect(parsed, isNotNull);
        expect(parsed!['eventId'], equals(testEvent.id));
        expect(parsed['title'], equals(testEvent.title));
        expect(parsed['location'], equals(testEvent.location));
      });
    });

    group('QR data round-trip', () {
      test('should maintain data integrity through encode and decode', () {
        // Generate QR data
        final qrData = qrService.generateEventQRData(testEvent);

        // Parse it back
        final parsed = qrService.parseQRData(qrData);

        expect(parsed, isNotNull);
        expect(parsed!['eventId'], equals(testEvent.id));
        expect(parsed['title'], equals(testEvent.title));
        expect(parsed['location'], equals(testEvent.location));
        
        final parsedStartTime = DateTime.parse(parsed['startTime']);
        expect(parsedStartTime, equals(testEvent.startTime));
      });
    });
  });
}

